### ISSUE TITLE
Why is there both README.md and README.rst?

### ISSUE THREAD

**Issue by alexmojaki** [pwwang/python-varname#16]
GitHub can render RST and PyPI can render markdown if you tell it to.

**Comment by pwwang** [comment]
`README.rst`, `requirements.txt`, and `setup.py` were automatically generated by `poetry`. What I need to maintain are just `README.md` and `pyproject.toml`. I am not sure when `PyPI` started to support markdown, or as good as it does for RST. I didn't find a perfect way to just send markdown to PyPI before I started using `poetry`, which takes care of that stuff. I have `requirements.txt` and `setup.py` included in the repo because sometimes github failed to show `Used By` without those files.

**Comment by alexmojaki** [comment]
OK, as long as the system works and you don't need to maintain both, not enough reason to change it.
