### ISSUE TITLE
bytecode_nameof should check for full=True

### ISSUE THREAD

**Issue by alexmojaki** [pwwang/python-varname#24]
If you try `eval("varname.nameof(a.b, full=True)")` you will get an error as expected, because the keyword argument changes the call bytecode.

However if you don't pass the keyword argument at the call site, you get the wrong result:

```python
import varname

def full_nameof(_):
    return varname.nameof(_, full=True, caller=2)

assert full_nameof(varname.nameof) == "varname.nameof"
assert eval("full_nameof(varname.nameof)") == "nameof"
```

This is based on the suggestion given in #23

**Comment by pwwang** [comment]
Yes, that's why I was saying in such an environment, only a single variable should be passed and no keyword arguments. And this definitely limits the use of `nameof`. And this is also why I was asking it is necessary to walk through the instructions to investigate this kind of `CALL_FUNCTION_KW` thing.

**Comment by alexmojaki** [comment]
The problem is that there is no `CALL_FUNCTION_KW`. `bytecode_nameof` just sees a normal call `full_nameof(varname.nameof)` and doesn't realise that the user asked for `full=True`. I'm not suggesting analysing the bytecode to get the full path, just refuse to use `bytecode_nameof` when `full=True`.

**Comment by pwwang** [comment]
Then where do we see that `full=True` in `bytecode_nameof`, by using that wrapped `full_nameof`?

**Comment by alexmojaki** [comment]
Yes, disable it in `nameof`.

**Comment by pwwang** [comment]
Sure, one of the caveats is that `eval('nameof(a.b, full=False)')` will still raise an error, as it sees `CALL_FUNCTION_KW` in `_bytecode_nameof`.

**Comment by pwwang** [comment]
24bb42ec727060488a1c3c177cf1d0e7d70d041d

**Comment by pwwang** [comment]
At commit: https://github.com/pwwang/python-varname/commit/a2493a46538573198b5ed1ff2fa721089316de4e

I have:
- Set the default value of `full` argument to `None`, so that we can detect whether user has passed `True` or `False` or this argument and neither is accepted for bytecode mode.
- According to that, given some _decent_ hints according to the filename of the source
- Separated tests for `nameof` that need to invoke `_bytecode_nameof` in a different test file, so that we can keep the main one clean for other tests.
- Other tiny fixes.

Let me know if you have any suggestions or comments.

I have created a dev branch and will try PR for future changes. Hope you could also help review the code before merging.

Thank you always for contributing and helping!

**Comment by alexmojaki** [comment]
Looks good!
